### ISSUE TITLE
Rename on google login

### ISSUE THREAD

**Issue by Leodenact** [Tsunamii/IVTool#1]
How do I get this to rename them instead of only listing their IV in cmd?

1.I opened the read me and typed in my username and pw for google login. 
2.I run the cmd with java -jar ivtool.jar

What am I missing to rename them? Shoul I write something in the cmd?

**Comment by zurroball** [comment]
java -jar ivtool.jar -r

that will rename them all that don't have nicknames already to their % and stats
add -f  if you want to rename ever pokemon, even with changed names.
[The syntax is here](https://github.com/Tsunamii/IVTool#syntax) if you want to read more
