### ISSUE TITLE
Google account null on second try

### ISSUE THREAD

**Issue by millertech** [Tsunamii/IVTool#4]
I ran the tool from the batch file and it did not have a pause. The screen disappeared and I missed all the data. Now when I try to rerun I get this:
C:\IVTool-master>java -jar ivtool.jar
D/GoogleLogin: Get user to go to:null and enter code:null

any ideas?

**Comment by Tsunamii** [comment]
seems like a problem with the api:
https://github.com/Grover-c13/PokeGOAPI-Java/issues/293

**Comment by h2xtreme** [comment]
The API bug was closed. They implemented a new method of authentication. Any chance to make this tool use the new version of the API?

**Comment by Tsunamii** [comment]
working on it already <3
once succesfully tested there will be a new version with much more features :)

**Comment by h2xtreme** [comment]
If you need help testing let me know

**Comment by h2xtreme** [comment]
ivtool.jar missing after latest commit?

**Comment by Tsunamii** [comment]
done :)
the jar file can now be found unter releases :)
