### ISSUE TITLE
"Unable to access jar file"

### ISSUE THREAD

**Issue by Olathurl** [Tsunamii/IVTool#5]
using the following CL:

java -jar ivtool.jar -user=GoogleNameHere -pass=GooglePassHere -r -out=output.csv

Have also tried:
java -jar ivtool.jar -user GoogleNameHere -pass GooglePassHere -r -out output.csv

as well as:
java -jar ivtool.jar -ptc -user=ptcNameHere -pass=ptcPassHere -r -out=output.csv

and lastly:
java -jar ivtool.jar -ptc -user ptcNameHere -pass ptcPassHere -r -out=output.csv

**Comment by Tsunamii** [comment]
Did your cmd shell point to the path of the ivtool.jar?

**Comment by russr123** [comment]
the JAR is ivtool_#####.jar.... you need to update the cmd line to the file name

**Comment by Olathurl** [comment]
:c i simply copied was was in the readme. will check naming ina sec ^_^

**Comment by Tsunamii** [comment]
thanks for the update :) glad it works
looks like I should add the ivtool.jar back to the repo since it causes more confusion than I thaught :D
