### ISSUE TITLE
Google log in

### ISSUE THREAD

**Issue by russr123** [Tsunamii/IVTool#6]
if you password has spaces, i assume you have to put it in with quotes?

java -jar ivtool_0.1.0.jar -user=USER@gmail.com -pass="PASS WITH SPACES" -r -out=IVstats-G.csv

when i do, the screen pukes this to fill it up

if your pass has a space in it, do you need to put it in " "
if you do, will it work?
when i do, it "looks like it logs in, but then pukes this out to fill the screen
at java.util.regex.Pattern$CharProperty.match(Unknown Source
at java.util.regex.Pattern$Branch.match(Unknown Source)
at java.util.regex.Pattern$GroupHead.match(Unknown Source)
at java.util.regex.Pattern$LazyLoop.match(Unknown Source)
at java.util.regex.Pattern$GroupTail.match(Unknown Source)
at java.util.regex.Pattern$BranchConn.match(Unknown Source)

**Comment by Tsunamii** [comment]
https://issues.apache.org/jira/browse/CLI-180 suggests using double quotes.
If this doesn't work I need to do some debugging tomorrow.

**Comment by russr123** [comment]
that may have worked, now i get 

Connection failed. Reason: svarzee.gps.gpsoauth.Gpsoauth$TokenRequestFailed
Check http://ispokemongodownornot.com/ to see if servers are down.

**Comment by Tsunamii** [comment]
will test everything tomorrow. seems like there are some more issues with the latest version :/

**Comment by Tsunamii** [comment]
next version will have the token and oauth system again, since this version caused way to much trouble

**Comment by COLDPOKEMONGO** [comment]
@Tsunamii alright.. I've been getting a protobuf error and constantly being asked to check if servers are down.

> Connection failed. Reason: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

**Comment by Tsunamii** [comment]
could you try the newest version? the ivtool.jar directly in the repo

**Comment by adamrgolf** [comment]
The newest ivtool.jar is working again with the token system. I'm glad you didn't have to revert all the way back and the output to csv function still works :) thanks!

**Comment by COLDPOKEMONGO** [comment]
Could you kindly update the readme? I got it to work again but I'm wondering if I'm doing it right as I still am keying in my details into the cmd line, just that now I've a refresh token :scream:

**Comment by Tsunamii** [comment]
just ommit pass and user it's ignored for google :)

google no token:
java -jar ivtool.jar [other arguments]

google with token:
java -jar ivtool.jar -token=blaaaaaaaaa [other arguments]
