### ISSUE TITLE
"fixed atk, def, sta calculation" 

### ISSUE THREAD

**Issue by russr123** [Tsunamii/IVTool#7]
0.1.0 numbers..
![image](https://cloud.githubusercontent.com/assets/20584235/17227254/7f110908-54db-11e6-9198-db80bb7d49f2.png)

0.1.1 numbers..

![image](https://cloud.githubusercontent.com/assets/20584235/17227292/a18bbe88-54db-11e6-9fff-16d525d427cc.png)

the new #'s look WAY out of wack

**Comment by Tsunamii** [comment]
But those new values are the correct values for the current level of the pokemon, I forgot to multiply with the cp modifier before.

```
	public double getAtk() {
		return (pokemon.getMeta()
				.getBaseAttack() + getIvAtk()) * pokemon.getCpMultiplier();
	}

	public double getDef() {
		return (pokemon.getMeta()
				.getBaseDefense() + getIvDef()) * pokemon.getCpMultiplier();
	}

	public double getSta() {
		return (pokemon.getMeta()
				.getBaseStamina() + getIvSta()) * pokemon.getCpMultiplier();
	}
```

**Comment by russr123** [comment]
so, the old numbers would be "if" it was at max CP?

**Comment by Tsunamii** [comment]
correct. same with the other values (damage / dmg per cp). but I thought It should show the current values since not everyone has the candies and stardust to level up to reach that maximum for each pokemon
