### ISSUE TITLE
Reset option not working with lastest release

### ISSUE THREAD

**Issue by agreian** [Tsunamii/IVTool#9]
java -jar ivtool_0.1.1.jar --reset --user "xxx@xxx.xxx" --pass "xxx"
Parsing failed. Reason: Unrecognized option: --reset
usage: ivtool [-ptc] -user <user> -pass <1234> [-r] [-f] [-out <file>]
 -d,--debug         show the debug messages
 -f,--force         forces the rename for pokemon that already have a
                    nickname
 -h,--help          print this message
 -o,--out <arg>     create an output file
    --pass <arg>    your ptc/google password
    --ptc           use your ptc account for login instead of google
 -r,--rename        rename every pokemon without a nickname
 -s,--star <arg>    star every pokemon with a iv % above the given
                    argument (doesn't work yet)
    --sleep <arg>   sleep time after each action in ms (default = 2000ms)
    --user <arg>    your ptc username / google email

java -jar ivtool_0.1.1.jar -reset --user "xxx@xxx.xxx" --pass "xxx"
Parsing failed. Reason: Unrecognized option: -reset
usage: ivtool [-ptc] -user <user> -pass <1234> [-r] [-f] [-out <file>]
 -d,--debug         show the debug messages
 -f,--force         forces the rename for pokemon that already have a
                    nickname
 -h,--help          print this message
 -o,--out <arg>     create an output file
    --pass <arg>    your ptc/google password
    --ptc           use your ptc account for login instead of google
 -r,--rename        rename every pokemon without a nickname
 -s,--star <arg>    star every pokemon with a iv % above the given
                    argument (doesn't work yet)
    --sleep <arg>   sleep time after each action in ms (default = 2000ms)
    --user <arg>    your ptc username / google email

**Comment by Tsunamii** [comment]
--reset was added with the latest .jar version in the repo. The 0.1.1 version doesn't have it.

**Comment by agreian** [comment]
So could you please make a new release ?

**Comment by russr123** [comment]
grab the ivtool.jar from here, not from the release page, and it works.. 
https://github.com/Tsunamii/IVTool
